version: '3.4'

services:
  db:
    image: postgres:16.2-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=itplanet
      - POSTGRES_PASSWORD=itplanet
      - POSTGRES_DB=itplanet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  itplanet:
    image: ${DOCKER_REGISTRY-}itplanet
    build:
      context: .
      dockerfile: ITPlanet/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=itplanet;User Id=itplanet;Password=itplanet;

volumes:
    postgres_data:
        name: 'postgres_data'